version: "3"
services:

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - localWeb

  cache:
    image: memcached
    container_name: cache
    hostname: cacheserver
    ports:
      - "11211:11211"
    networks:
      - localWeb
      
  server:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    networks:
      - localWeb

networks:
  localWeb:

